name       : haskell-distributive
version    : 0.5.3
release    : 3
source     :
    - https://hackage.haskell.org/package/distributive-0.5.3/distributive-0.5.3.tar.gz : 9173805b9c941bda1f37e5aeb68ae30f57a12df9b17bd2aa86db3b7d5236a678
license    : BSD-3-Clause
component  : programming.haskell
summary    : Distributive functors -- Dual to Traversable
description: |
    Distributive functors -- Dual to Traversable
builddeps  :
    - ghc-devel
    - haskell-base-orphans
    - haskell-cabal-install
    - haskell-tagged
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    export GHCV=$(ghc --numeric-version)
    %cabal_install
    cp $installdir/usr/lib64/x86_64-linux-ghc-$GHCV/* $installdir/usr/lib64/ghc-$GHCV/distributive-$version/
    rm -rf $installdir/usr/lib64/x86_64-linux-ghc-$GHCV
    %cabal_register
