name       : haskell-distributive
version    : 0.5.2
release    : 1
source     :
    - http://hackage.haskell.org/package/distributive-0.5.2/distributive-0.5.2.tar.gz : ade2be6a5e81950ab2918d938037dde0ce09d04dc399cefbf191ce6cb5f76cd9
license    : BSD-3-Clause
component  : programming.haskell
summary    : Distributive functors -- Dual to Traversable
description: |
    Distributive functors -- Dual to Traversable
builddeps  :
    - ghc-devel
    - haskell-base-orphans
    - haskell-cabal-install
    - haskell-tagged
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
