name       : haskell-distributive
version    : 0.6.2
release    : 5
source     :
    - https://hackage.haskell.org/package/distributive-0.6.2/distributive-0.6.2.tar.gz : 824ee271ded433ce6c61fe890c784642b7e20ffa4082fca609da54e7dcfc23c9
license    : BSD-3-Clause
component  : programming.haskell
summary    : Distributive functors -- Dual to Traversable
description: |
    Distributive functors -- Dual to Traversable
builddeps  :
    - haskell-base-orphans-devel
    - haskell-cabal-install
    - haskell-tagged-devel
rundeps    :
    - devel:
        - haskell-base-orphans-devel
        - haskell-tagged-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
